#INITIAL SETTINGS


#********* Uncomment this section when running the iris dataset *******
# number of runs of continuation method runs
#n_continuation: 1
# number of points that hopefully belong to the pareto front
#n_pareto_grad: 25 #5
# number of points that hopefully belong to the pareto front
#n_pareto_prox: 18
# number of iterations for prediction
#n_predictor:  30
# Set number of training epochs for corrector
#n_corr: 500
# Set number of training epochs for first run
#n_corr_first: 10000
# number of iterations for prediction loss_minimization
#n_predictor_loss: 30
#n_corrector_loss: 500




#********* Uncomment this section when running the deterministic approach mnist *******
# number of runs of continuation method runs
#n_continuation: 1
# number of points that hopefully belong to the pareto front
#n_pareto_grad: 25 #5
# number of points that hopefully belong to the pareto front
#n_pareto_prox: 18
# number of iterations for prediction
#n_predictor:  50
# Set number of training epochs for corrector
#n_corr: 500
# Set number of training epochs for first run
#n_corr_first: 5000 
# number of iterations for prediction loss_minimization
#n_predictor_loss: 50
#n_corrector_loss: 500



#***** Stochastic mnist**********************#

# number of runs of continuation method runs
n_continuation: 1
# number of points that hopefully belong to the pareto front
n_pareto_grad: 25 #5
# number of points that hopefully belong to the pareto front
n_pareto_prox: 18
# number of iterations for prediction
n_predictor:  7
# Set number of training epochs for corrector
n_corr: 20 #100  #500
# Set number of training epochs for first run
n_corr_first: 500 


# number of iterations for prediction loss_minimization
n_predictor_loss: 7
n_corrector_loss: 20